adventureworks:
  target: snowflake
  outputs:
    snowflake:
      type: snowflake
      account: xxxxx.ap-southeast-1
      user: PC_COALESCE_USER
      password: xxxxx
      role: SYSADMIN
      database: DEV_SOURCES
      warehouse: PC_COALESCE_WH
      schema: PUBLIC
      threads: 5
      client_session_keep_alive: False
      query_tag: demo
